[task-2] Header-logo
vasiliy-shch/online-shop pull request #6
Opened 2023-10-04 10:42 UTC by vasiliy-shch

Разместить в шапке страницы логотип

2023-10-13 11:38 UTC, vasiliy-shch commented
* Добавлена папка Images, для формирования базы иконок/картинок/логотипов, использующихся в проекте;
* Создан компонент HeaderShop (шапка сайта), в него подключен компонент HeaderLogo;
* Так как лого в сборе у меня не было, сделал два компонента: HeaderImage и HeaderBrand, в первом соответственно svg изображение логотипа, во втором текстовое название (из плюсов такого подхода - можем поменять название и картину в любой в момент, логотип соберется, также его теперь можно переиспользовать в разных местах)

2023-10-13 11:49 UTC, SHTIKOV requested changes

2023-10-13 11:49 UTC, SHTIKOV commented on pages/index.vue
> +  <HeaderShop></HeaderShop>
Перенеси это лучше в layout, что бы на всех страницах этот хедер был а не только на главной

https://nuxt.com/docs/guide/directory-structure/layouts

2023-10-13 11:50 UTC, SHTIKOV commented on index2.html
эт очто за файл?) напомню, что нужно самому делать ревью и быть уверенным, что твой код достоен что бы его приняли в работу на проект) отговорки не принимаются) что за index2.html

2023-10-13 11:51 UTC, SHTIKOV commented on components/HeaderShop.vue
> +  data () {
у тебя нет переменных для чего тогда `data`?) в других файлах тоже убери

2023-10-16 10:31 UTC, SHTIKOV commented on components/HeaderBrand.vue
> +export default {
По сути смысловой нагрузки это тоже не несет, поэтому думаю можно дропнуть)

2023-10-16 10:36 UTC, SHTIKOV commented on pages/index.vue
> +    <page slot="header"></page>
т.е. на каждой странице что бы появилась шапка нужно будет каждый раз прописывать эту строчку?) не нужно это здесь, а в лейауте должен быть что то типа того:

```html
<!-- layouts/default.vue -->
<template>
  <div class="main-wrapper">
    <AppHeader />
    <slot />
    <AppFooter />
  </div>
</template>
```

2023-10-16 10:36 UTC, SHTIKOV commented on pages/index.vue
> +    <page slot="header"></page>
если что это просто пример

2023-10-18 06:29 UTC, merged